import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export async function getServerSideProps() {

  const res = await fetch("https://jsonplaceholder.typicode.com/posts")
  const data = await res.json()

  return {
    props: {
      posts: data
    }, // will be passed to the page component as props
  }
}

export default function Home({posts}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {posts.map((post => (
        <Link href={"/" + post.id} key={post.id}>
          <p >{post.title}</p>
          <br></br>
        </Link>
      )))}
    </>
  )
}
